apiVersion: v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 147023380632.dkr.ecr.us-east-2.amazonaws.com/hello-world:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
