apiVersion: extentions/v1beta1
kind: Deployment
metadata:
  name: sureshwebapp
spec:
  replicas: 2  
  template:
    metadata:
      labels:
        app: sureshwebapp
    spec:
      containers:
      - name: sureshwebapp
        image: suresh2020dev/sureshwebapp:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: sureshwebapp
spec:
  selector:
    app: sureshwebapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
